### ISSUE TITLE
Error: Value for unconfigurable attribute

### ISSUE THREAD

**Issue by miguelalb** [hashicorp/learn-terraform-lambda-api-gateway#8]
https://github.com/hashicorp/learn-terraform-lambda-api-gateway/blob/ed4863b30b691e6e289a3b5231f80edb572370b7/main.tf#L32

When running Terraform Apply I get the following error:
`Error: Value for unconfigurable attribute
│ 
│   with aws_s3_bucket.lambda_bucket,
│   on main.tf line 32, in resource "aws_s3_bucket" "lambda_bucket":
│   32:   acl           = "private"
│ 
│ Can't configure a value for "acl": its value will be decided automatically
│ based on the result of applying this configuration.`

This is most likely due to deprecated acl parameter. 
**Workaround/fix:** According to [AWS S3 bucket provider docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket) ACL can be configured as a standalone resource [aws_s3_bucket_acl](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_acl)

**Comment by yoguib** [comment]
new error: │ Error: error creating S3 Bucket (learn-terraform-functions-) Ownership Controls: NoSuchBucket: The specified bucket does not exist
│       status code: 404

**Comment by robin-norwood** [comment]
Fixed, thanks!
